version: '3.8'
services:
  # Poste.io IMAP server (same as before)
  posteio:
    image: analogic/poste.io:latest
    container_name: posteio
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./posteio/data:/data
      - ./dovecot.conf:/etc/dovecot/conf.d/99-custom-config.conf

    environment:
      - "TZ=America/New_York" # Set your timezone (e.g., "America/New_York")


  # Custom Roundcube webmail client
  custom_roundcube:
    build:
        context: ./custom_roundcube
    container_name: custom_roundcube
    ports:
      - "8080:80"
    depends_on:
      - db
      volumes:
        - ./custom_roundcube/:/var/www/html/
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=posteio
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=posteio
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_IMAP_AUTH_TYPE=LOGIN
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=db
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER=root
      - ROUNDCUBEMAIL_DB_PASSWORD=mysecretpassword
      - ROUNDCUBEMAIL_DB_NAME=roundcube


  # Roundcube webmail client
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./roundcube-data:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=posteio
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=posteio
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_IMAP_AUTH_TYPE=LOGIN
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=db
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER=root
      - ROUNDCUBEMAIL_DB_PASSWORD=mysecretpassword
      - ROUNDCUBEMAIL_DB_NAME=roundcube

  # MySQL database
  db:
    image: mysql:latest
    container_name: roundcube_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: roundcube
    volumes:
      - ./mysql_data:/var/lib/mysql

