version: '3.8'
services:
  # Poste.io IMAP server (same as before)
  posteio:
    image: analogic/poste.io:latest
    container_name: posteio
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./posteio/data:/data
      - ./dovecot.conf:/etc/dovecot/conf.d/99-custom-config.conf

    environment:
      - "TZ=America/New_York" # Set your timezone (e.g., "America/New_York")


  # # Custom Roundcube webmail client
  # custom_roundcube:
  #   build:
  #       context: ./custom_roundcube
  #   container_name: custom_roundcube
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./custom_roundcube/:/var/www/html/
  #   environment:
  #     - ROUNDCUBEMAIL_DEFAULT_HOST=posteio
  #     - ROUNDCUBEMAIL_DEFAULT_PORT=143
  #     - ROUNDCUBEMAIL_SMTP_SERVER=posteio
  #     - ROUNDCUBEMAIL_SMTP_PORT=587
  #     - ROUNDCUBEMAIL_IMAP_AUTH_TYPE=LOGIN
  #     - ROUNDCUBEMAIL_DB_TYPE=pgsql  # Change the database type to PostgreSQL
  #     - ROUNDCUBEMAIL_DB_HOST=db  # Use the service name as the hostname
  #     - ROUNDCUBEMAIL_DB_PORT=5432  # PostgreSQL port is 5432
  #     - ROUNDCUBEMAIL_DB_USER=roundcube  # Create a new user for Roundcube
  #     - ROUNDCUBEMAIL_DB_PASSWORD=roundcube  # Set your preferred password
  #     - ROUNDCUBEMAIL_DB_NAME=roundcube_db  #

      # Roundcube webmail client
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./roundcube-data:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=posteio
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=posteio
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_IMAP_AUTH_TYPE=LOGIN
      - ROUNDCUBEMAIL_DB_TYPE=pgsql  # Change the database type to PostgreSQL
      - ROUNDCUBEMAIL_DB_HOST=db  # Use the service name as the hostname
      - ROUNDCUBEMAIL_DB_PORT=5432  # PostgreSQL port is 5432
      - ROUNDCUBEMAIL_DB_USER=roundcube  # Create a new user for Roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube  # Set your preferred password
      - ROUNDCUBEMAIL_DB_NAME=roundcube_db  #

 # PostgreSQL database
  db:
    image: postgres:latest
    container_name: roundcube_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: roundcube  # This should match the ROUNDCUBEMAIL_DB_USER above
      POSTGRES_PASSWORD: roundcube  # This should match the ROUNDCUBEMAIL_DB_PASSWORD above
      POSTGRES_DB: roundcube_db  # This should match the ROUNDCUBEMAIL_DB_NAME above
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


